### ISSUE TITLE
Windows Error after playing audio. flutter: UnimplementedError: disposeAllPlayers() has not been implemented.

### ISSUE THREAD

**Issue by hogdamian** [bdlukaa/just_audio_libwinmedia#14]
After playing audio on windows i get following Error.
 flutter: UnimplementedError: disposeAllPlayers() has not been implemented.

**Comment by ryanheise** [comment]
This is just a warning, since not all platforms are required to implement `disposeAllPlayers`. It is used only to dispose of players on a hot reload.

However, it shouldn't be difficult to implement, I guess.

**Comment by hogdamian** [comment]
On Windows i have the problem that i can play audio once and after it its not possible to play another audio anymore.

**Comment by ryanheise** [comment]
I don't think that's related to the `disposeAllPlayers` message since that should only appear once when the app starts. (Maybe it's best to open a new issue if it's not related to this.)

**Comment by DominicOrga** [comment]
I'm also experiencing this issue when building my app on Windows. In my case, no audio is coming out at all.

Here's the error:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method disposeAllPlayers on channel com.ryanheise.just_audio.methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175)
<asynchronous suspension>
#1      MethodChannelJustAudio.disposeAllPlayers (package:just_audio_platform_interface/method_channel_just_audio.dart:29)
<asynchronous suspension>
```

Here's the result of my `flutter doctor -v`.

<details>

```
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.19042.1466], locale en-PH)
    • Flutter version 2.10.2 at C:\Users\Raphael\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (5 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32210.238
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\Raphael\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.1466]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by ryanheise** [comment]
What I was trying to say above is that these aren't all the same issue.

**Comment by DominicOrga** [comment]
Oh okay sorry about that. I'll try doing some further investigation with my issue and determine whether to file a bug report here or at the `just_audio` package.

**Comment by ryanheise** [comment]
Hmm, looking at it further, I'm not clear why it is being reported as an unhandled exception since the only place `disposeAllPlayers` is called is within a try/catch block in just_audio's `lib/just_audio.dart`. Also, from memory I didn't think just_audio_libwinmedia was implemented based on method channels since it is a pure Dart implementation. That is rather confusing as I would only expect that sort of error on the method channel-based implementations such as iOS/macOS/Android.

**Comment by gkovac42** [comment]
Also getting this error as soon as I try to play any audio file, I can't get anything to play at all. Is there an update on this?

**Comment by hogdamian** [comment]
Yes i have found a solution.
Let me know if you still need it

**Comment by GrimDevStudio** [comment]
> Yes i have found a solution. Let me know if you still need it

Yes, please.

**Comment by gkovac42** [comment]
I could use it, yes. Thanks in advance!

**Comment by hogdamian** [comment]
Please provide your implementation.

**Comment by bdlukaa** [comment]
I have started implementing a native player using platform channels for the Windows platform here: https://github.com/bdlukaa/just_audio, under https://github.com/bdlukaa/just_audio/tree/master/just_audio_windows

It performs a lot better and doesn't have all these bugs that libwinmedia has. Also, libwinmedia is now deprected and, once `just_audio_windows` gets published, `just_audio_libwinmedia` will be deprecated as well.

I haven't got the time to work on this yet, but I can try to have some progress on it this weekend and get you to the updates on https://github.com/ryanheise/just_audio/issues/103

**Comment by gkovac42** [comment]
That's great news! From what I could gather, all currenty existing audio plugins for Windows are lacking in one way or another. Could you please keep me up-to-date with this? I have a commercial Flutter Windows project that depends on the ability to play short audio files without issues on as much different Windows versions and builds as possible. I'll gladly throw a donation your way if you would accept it, just let me know where.
